### ISSUE TITLE
upadate 3.9 sdk

### ISSUE THREAD

**Issue by master88wi** [keenetic/keenetic-sdk#12]
Please let me know when the next update for version 3.9 will be available?

**Comment by apolo2012** [comment]
Unfortunately no response, keenetic forgot its customers. At the beginning, I recommended their products to everyone for their constant updates and attention to public requests. But now I'm starting to doubt them. Too bad, it looked like a promising company and I could see a strong future for them in the European market. :(

**Comment by MarvinOl** [comment]
Keenetic, being a Russian company, does not want anyone to be able to use the SDK to verify that there are no backdoors in the routers they sell on EU Amazon marketplaces. Keenetic routers running firmware newer than 3.8.3 should be considered to include backdoors used by Russian Government Agencies.

**Comment by apolo2012** [comment]
I think you are right, anyway with their current strategy, the next device will definitely not be keenetic.

**Comment by master88wi** [comment]
**MarvinOl**
Hong Kong, North Point
this Russia?)))

**Comment by eyudin** [comment]
All versions 3.8 and 3.9 are uploaded.
Please contact official support for a quick response.

**Comment by helpmebro911** [comment]
> All versions 3.8 and 3.9 are uploaded. Please contact official support for a quick response.

pls sdk 4.2
