### ISSUE TITLE
The resulting firmware name contains an incorrect version number

### ISSUE THREAD

**Issue by dartraiden** [keenetic/keenetic-sdk#15]
Original firmware: `KN-1811_stable_4.00.C.4.0-0.bin`

Resulting firmware: /bin/mt7622/20231016_2350_Firmware-KN-1811-`0.00.A.0.0-0`.bin

**Comment by FedorovSerafim** [comment]
git tag -a 4.00.C.4.0-0 -m "Release 4.00.C.4.0-0"

**Comment by eyudin** [comment]
I added the missing tags with changes.
Since packages in SDK may change between versions, it is incorrect to build from a branch without a tag or a manually set tag.
Thanks!
